[package]
name = "boolean_operator"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
ciborium = "0.2"
wasmparser = "0.219"
wasm-encoder = { version = "0.219", features = ["wasmparser"] }
