[package]
name = "lua_script_operator"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
walrus = "0.24"
full_moon = "2.1"
serde = { version = "1", features = ["derive"] }
ciborium = "0.2"
thiserror = "2"
