[package]
name = "lua_script_operator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
walrus = "0.20"
full_moon = "0.18"
serde = { version = "1", features = ["derive"] }
ciborium = "0.2"
thiserror = "1"
