[package]
name = "translate_operator"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
walrus = "0.23"
serde = { version = "1", features = ["derive"] }
ciborium = "0.2"
